spring:
  application:
    name: mvd-fias-manual-updater
  datasource:
    username: ${APPFIAS_PG_USER:put_db_user_creds_via_program_args}
    password: ${APPFIAS_PG_PASSWORD:put_db_password_via_program_args}
    url: "${APPFIAS_PG_URL:put_db_url_via_command_line_args}"
    hikari:
      maximum-pool-size: ${APPFIAS_PG_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${APPFIAS_PG_MINIMUM_IDLE:5}
      connection-timeout: ${APPFIAS_PG_CONNECTION_TIMEOUT:30000}
  batch:
    initialize-schema: never
    job:
      enabled: false
    table-prefix: "FIASUPDATE.BATCH_"
fias:
  schema:
    name: ${APPFIAS_SCHEMA_NAME:fias_reserve}